line-length = 88
target-version = "py312"

[lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # convention
    "B",  # flake8-bugbear
]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
